name: ff_annotation_route_library
description: The library for ff_annotation_route,support both null-safety and non-null-safety.
version: 2.0.0
homepage: https://github.com/fluttercandies/ff_annotation_route_library

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ff_annotation_route_core: ^2.0.0
  flutter:
    sdk: flutter

